### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by jrosen48** [tylerhall/tadpoles-api#1]
just wanted to say _thanks_ - this is super well-documented and easy-to-use, even for a PHP neophyte! So glad there was a way to archive these photos. Agree tadpoles isn't great! Our daycare provider switched to an _even worse_ app for awhile, and I was surprised that it may be glad that they returned to it. Anyway, thanks!

**Comment by tylerhall** [comment]
Thanks, @jrosen48! Always great to hear little projects of mine like this one are useful to others.
