### ISSUE TITLE
You're a genie.

### ISSUE THREAD

**Issue by talzu** [tylerhall/tadpoles-api#2]
Just wanted to say thank you.
This really helped me in a situation that sounded very much like the situation you had when you came up with this script, and it worked right out of the box. so.. THANK YOU! Now my kids' memories are safe and sound outside of the weird tadpoles app ;)

**Comment by tylerhall** [comment]
Ahh, that's great to hear, @talzu! I can't imagine there are many people out there who need this script, so I'm thrilled when I hear it was useful for someone.
